//GENRES
export const GENRE_SELECT = 'GENRE_SELECT'
//RAITING
export const STARS_RAITING_SELECT = 'STARS_RAITING_SELECT'
export const STARS_RAITING_RESET = 'STARS_RAITING_RESET'
//PAGE AMOUNT
export const PAGE_AMOUNT_RANGE_SELECT = 'PAGE_AMOUNT_RANGE_SELECT'
export const PAGE_AMOUNT_RANGE_RESET = 'PAGE_AMOUNT_RANGE_RESET'
//SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
//WISH LIST
export const WISH_LIST_ADD = 'WISH_LIST_ADD'
export const WISH_LIST_REMOVE = 'WISH_LIST_REMOVE'
export const WISH_LIST_CLEAR = 'WISH_LIST_CLEAR'
